name: picture_d
channels:
  - conda-forge
dependencies:
  - _python_abi3_support=1.0
  - aiobotocore=2.25.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - appnope=0.1.4
  - astropy=7.1.1
  - astropy-base=7.1.1
  - astropy-iers-data=0.2025.11.3.0.38.37
  - asttokens=3.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.8
  - aws-c-common=0.12.5
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.7
  - aws-c-io=0.23.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.0
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - beautifulsoup4=4.14.2
  - bleach=6.2.0
  - botocore=1.40.49
  - bottleneck=1.6.0
  - bqplot=0.12.45
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.10.5
  - cffi=2.0.0
  - click=8.3.0
  - cloudpickle=3.1.2
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.12.12
  - cycler=0.12.1
  - dask-core=2025.10.0
  - debugpy=1.8.17
  - decorator=5.2.1
  - dill=0.4.0
  - executing=2.2.1
  - fonttools=4.60.1
  - freetype=2.14.1
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - gast=0.4.0
  - gflags=2.2.2
  - glog=0.7.1
  - h2=4.3.0
  - h5py=3.15.1
  - hdf5=1.14.6
  - hpack=4.1.0
  - html5lib=1.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipydatagrid=1.4.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jmespath=1.0.1
  - jplephem=2.23
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.16
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libcxx=21.1.5
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=22.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.5
  - locket=1.0.0
  - lz4-c=1.10.0
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - mpmath=1.3.0
  - multidict=6.6.3
  - multiprocess=0.70.18
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - numpy=2.3.4
  - openjpeg=2.5.4
  - openssl=3.5.4
  - orc=2.2.1
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - partd=1.4.2
  - pathos=0.3.4
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.2
  - platformdirs=4.5.0
  - pox=0.3.6
  - ppft=1.7.7
  - prettytable=3.16.0
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py2vega=0.6.1
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pycparser=2.22
  - pyerfa=2.0.1.5
  - pyfftw=0.15.1
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.12.5
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - re2=2025.11.05
  - readline=8.2
  - s3fs=2025.10.0
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - stack_data=0.6.3
  - tk=8.6.13
  - toolz=1.1.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - traittypes=0.2.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - uncompresspy=0.4.1
  - unicodedata2=17.0.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - webencodings=0.5.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - wrapt=1.17.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - coloredlogs==15.0.1
      - fast-histogram==0.14
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - humanfriendly==10.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - ml-dtypes==0.5.3
      - mpl-scatter-density==0.8
      - networkx==3.5
      - onnx==1.19.1
      - onnx-ir==0.1.12
      - onnxruntime==1.23.2
      - onnxscript==0.5.6
      - protobuf==6.33.0
      - sympy==1.14.0
      - torch==2.9.0
      - torchvision==0.24.0
